- README.md
update README with troubleshooting step in case of Snyk API returning 404.
- [Link to issue](https://github.com/snyk-tech-services/backstage-plugin-snyk/issues/11)
> docs: Add pathRewrite troubleshooting to readme

- README.md
> docs: update README install instructions

- .circleci/config.yml
- README.md
> syncing dev back with main after shenanigans with semantic release

- .clabot
Adds contributor to clabot file
> chore: add contrib to clabot

- package.json
- yarn.lock
The snyk backstage plugin does not work with current versions of backstage. This change updates the dependencies to make it work again.
Fixes #36
> Updates snyk plugin to use recent backstage

- .clabot
- package.json
- yarn.lock
Bumps deps as in https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/53
> fix: bump backstage core deps

- .snyk
- package.json
- yarn.lock
> fix: fix vulnerabilities

- .snyk
- package.json
- yarn.lock
> release changes

- package.json
Update @backstage/catalog-model to version 0.9.9
> Update @backstage/catalog-model to verison 0.9.9

- README.md
- package.json
- src/components/SnykEntityComponent/index.ts
- src/index.ts
- yarn.lock
Adds check to determine if plugin is applicable to entity (check if the required elements are in the yaml)
> feat: add issnykavailable check if applicable to entity

- package.json
- yarn.lock
> chore: upgrade @backstage/plugin-catalog-react

- package.json
bump dep without lockfile changes
> fix: rm private registry refs

- package.json
- yarn.lock
> fix: bump deps to fix bugs

- README.md
Mark the project as no longer maintained
> docs: mark the project as not maintained

- package.json
- yarn.lock
Bump dependencies to latest to skip vulnerable package versions
> chore: bump dependencies to latest

- README.md
Syntax highlighting in README, contribution brought in from: https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/89
> chore: Add syntax highlighting to readme.

- README.md
> docs: mark inactively maintained

- yarn.lock
Re-lock the lockfile to get latest deps within range
> chore: re-lock lockfile to get latest deps

- README.md
Quick instruction fix for Issues #118
> doc: update README install instructions

- README.md
Corrects inaccurate instructions for the token
> docs: update readme token instructions

- .circleci/config.yml
- package.json
- yarn.lock
Updates env var for snyk token
> chore: update circleci env var

- src/components/SnykEntityComponent/SnykOverviewComponent.tsx
> chore: cleanup comment line

- README.md
Updates README with migration steps to v2.
> docs: add migration steps from v1 to v2

- src/api/index.ts
- src/components/SnykEntityComponent/SnykEntityComponent.tsx
- src/components/SnykEntityComponent/snykTab.tsx
- src/types/orgsTypes.ts
> fix: make project links valid and pull up to 100 projects

- test/fixtures/catalog-multiple-targets-project-id-and-exclusion.yaml
- test/fixtures/catalog-multiple-targets.yaml
- test/fixtures/catalog-project-ids.yaml
- test/fixtures/catalog-project-slug-goof.yaml
- test/fixtures/catalog-target-id-goof.yaml
- test/fixtures/catalog-target-name-java-goof.yaml
> chore: push some test fixtures

- README.md
- src/api/index.ts
- src/components/SnykEntityComponent/SnykEntityComponent.tsx
- src/components/SnykEntityComponent/SnykOverviewComponent.tsx
- src/components/SnykEntityComponent/index.ts
- src/components/SnykEntityComponent/snykTab.tsx
- src/config.ts
Adds support for multiple targets, multiple project IDs and project IDs based exclusion, all still from a single org, not cross org support.
> feat: multitargets support & project ids import and exclusion

- README.md
Fix reference to org-name in the README
> Fix reference to org-name in the README

- .clabot
> chore: add silthus to cla

- .clabot
> chore: add nnillni to cla bot

- config.d.ts
- src/api/index.ts
- src/components/SnykEntityComponent/SnykOverviewComponent.tsx
- src/components/SnykEntityComponent/SnykTab.tsx
- src/types/unifiedIssuesTypes.ts
Fixes #176.
Updated issues api version to include latest version, separated from other APIs.
> fix: counts to exclude resolved and ignored

- src/api/index.ts
Should address issue mentioned in #175 for corner case.
> fix: throw err if no target ids found & no load all projs

- README.md
- src/api/index.ts
- src/types/targetsTypes.ts
Releases fix to ignore situations for orgs without matching targets
> release fix

- .clabot
Add @SnykOleg and @stefanbuck-snyk
> Add SnykOleg and stefanbuck-snyk to CLA file

- package.json
- src/api/SnykApiClient.ts
Updates the User-Agent version dynamically in SnykApiClient.ts based on package version for consistency and improved version management.
To run this locally:
1. Clone the repository.
2. Install dependencies with `npm install`.
3. Review changes in SnykApiClient.ts and package.json.
4. Ensure the User-Agent version is correctly set.
5. Run tests to verify changes.
> feat: set User-Agent version based on package version

- .circleci/config.yml
- .clabot
- package.json
- src/components/SnykEntityComponent/SnykTab.tsx
- tsconfig.json
- yarn.lock
Adds contributors to cla file.
> fix: add contributors to cla
